annotations:
  min_scale_version: 24.10.2.2
app_version: 1.0.0
capabilities: []
categories:
  - media
changelog_url: https://github.com/ParsonLabs/parson/releases
date_added: "2026-07-20"
description: Parson is a self-hosted, local-first music server and player.
home: https://github.com/ParsonLabs/parson
host_mounts: []
icon: https://media.sys.truenas.net/apps/parson/icons/icon.svg
keywords:
  - audio
  - media
  - music
  - self-hosted
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
  - email: dev@truenas.com
    name: truenas
    url: https://www.truenas.com/
name: parson
run_as_context:
  - description: Container [parson] runs as the non-root user bundled in the image.
    gid: 10001
    group_name: parson
    uid: 10001
    user_name: parson
screenshots:
  - https://media.sys.truenas.net/apps/parson/screenshots/screenshot1.png
  - https://media.sys.truenas.net/apps/parson/screenshots/screenshot2.png
sources:
  - https://github.com/ParsonLabs/parson
  - https://github.com/ParsonLabs/parson/pkgs/container/parson-music
title: Parson
train: community
version: 1.0.0
